### PR TITLE
Add support for OpenAI, Palm, Cohere, AI21, Aleph Alpha, TogetherAI, etc.

### PR DESCRIPTION
**Pull request by ghost**
Hi @xzyaoi 

Saw you support Anthropic. I'm working on litellm (simple library to standardize LLM API Calls - https://github.com/BerriAI/litellm) and was wondering if we could be helpful.

I added support for the providers listed above by replacing the HTTP API call with completion. The code is pretty similar to the OpenAI class - as litellm follows the same pattern as the openai-python sdk.

Would love to know if this helps.

Happy to add additional tests / update documentation, if the initial PR looks good to you.

### CODE REVIEW

**Comment by xzyaoi** [comment]
@krrishdholakia looks good to me! I've merged. Another update will follow to include litellm into requirements.txt.

In the meanwhile, just curious if it is possible to add our own inference endpoint to litellm? You can test it with:

```
import json
import requests

URL = "https://api.autoai.dev/inference"

def inference():
    resp = requests.post(URL, json={
        'model': 'meta-llama/Llama-2-13b-hf',
        'params': {
            'prompt': ["The capital of France is P"],
            'max_tokens': 32,
            'temperature': 0.7,
            'top_p': 1.0,
            'top_k': 40,
        }
    })
    resp = resp.json()
    return resp

if __name__ == "__main__":
    res = inference()
    print(res)
```
The expected output is:
```
{'data': [{'prompt': 'The capital of France is P', 'output': ['The capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France is PARIS.\nThe capital of France'], 'params': {'temperature': 0.7, 'top_k': 40, 'top_p': 1}}], 'message': 'ok'}
```

**Comment by ghost** [comment]
I'll add support for this later today @xzyaoi

**Comment by ishaan-jaff** [comment]
@xzyaoi added support for custom endpoints to litellm:

**support is active for litellm versions 0.1.538 or higher** 

Example usage:
```python
from litellm import completion 

response = completion(
    model="custom/meta-llama/Llama-2-13b-hf", 
    messages= [{"content": "what is custom llama?", "role": "user"}],
    temperature=0.2,
    max_tokens=10,
    api_base="https://api.autoai.dev/inference",
    request_timeout=300, # optional
)
print("got response\n", response)
```

notebook: https://colab.research.google.com/drive/1-LBTmUnGsOjIeZF6XvXf0ud1vwnDLya-?usp=sharing
docs: https://docs.litellm.ai/docs/providers/custom

**Comment by ishaan-jaff** [comment]
would love to know if you have any feedback or how we can make litellm better for you

- Is it okay if we add https://api.autoai.dev/inference to our docs as an example ? (happy to change it if you'd prefer)

**Comment by xzyaoi** [comment]
Hi @ishaan-jaff,
> would love to know if you have any feedback or how we can make litellm better for you
> 
> * Is it okay if we add https://api.autoai.dev/inference to our docs as an example ? (happy to change it if you'd prefer)

Definitely! It sounds good to me. I will also add litellm to our docs later this week as an example to issue queries.

**Pull request merged**
